[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerContext = "."

[deploy]
startCommand = "sh -c 'pnpm drizzle-kit push && node dist/main.js'"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10