[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'pnpm drizzle-kit push && node dist/main.js'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10